# Generated by Django 5.0.3 on 2024-06-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guidedata',
            name='carName',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='guidedata',
            name='trackName',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
