# Generated by Django 5.0.3 on 2024-06-23 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_alter_guidedata_carname_alter_guidedata_trackname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedata',
            name='carName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guides.car'),
        ),
        migrations.AlterField(
            model_name='guidedata',
            name='trackName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guides.track'),
        ),
    ]
