# Generated by Django 5.0.3 on 2024-07-20 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_alter_guidedata_carname_alter_guidedata_trackname'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarFrontLook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='car_front_looks')),
                ('carId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guides.car')),
            ],
        ),
    ]
