# Generated by Django 5.0.3 on 2024-07-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userguide',
            name='pass_time',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
