# Generated by Django 5.0.3 on 2024-07-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userguide',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
