# Generated by Django 5.0.3 on 2024-07-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userguide_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userguide',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
