# Generated by Django 5.0.3 on 2024-08-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userguide_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userguide',
            name='rating',
        ),
        migrations.AddField(
            model_name='userguide',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userguide',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
