# Generated by Django 5.0.3 on 2024-08-29 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userguiderate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userguide',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='userguide',
            name='likes',
        ),
        migrations.AddField(
            model_name='userguide',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserGuideRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('disliked', models.BooleanField(default=False)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userguide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'guide')},
            },
        ),
        migrations.DeleteModel(
            name='UserGuideRate',
        ),
    ]
