# Generated by Django 5.0.3 on 2024-08-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_userguide_dislikes_remove_userguide_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userguide',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userguide',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
